(move port river)
(steal_boat river)
(move river woods)
(acquire_at woods wood)
(fight_with_bear )
(move woods river)
(move river port)
(craft_at port bear_skin golden_coin)
(sail port sea)
(craft boat wood golden_coin karavela)
(defeat_pirates )
(sail sea port)
(move port town)
(cleanse_by_money )
(move town academy)
(study_for_captain )
(become_admiral )
; cost = 17 (unit cost)
