(move port river)
(move river woods)
(acquire_at woods flowers)
(acquire_at woods wood)
(make_boat )
(fight_with_bear )
(move woods river)
(move river port)
(craft_at port bear_skin golden_coin)
(move port town)
(invest town golden_coin golden_brick)
(move town port)
(sail port lighthouse)
(fascinate_girlfriend )
(sail lighthouse sea)
(acquire_at sea pearl)
(sail sea island)
(craft golden_brick pearl ring)
(get_married )
; cost = 19 (unit cost)
