(acquire_at port golden_grain)
(move port pub)
(craft_at pub golden_grain alcohol)
(move pub port)
(move port river)
(steal_boat river)
(move river woods)
(acquire_at woods wood)
(fight_with_bear )
(trade_at_shady woods alcohol map)
(move woods river)
(move river port)
(craft_at port bear_skin golden_coin)
(sail port sea)
(sail sea island)
(craft_at island map cocaine)
(sail island sea)
(craft boat wood golden_coin karavela)
(defeat_pirates )
(sail sea port)
(meet_with_smuglers )
(move port pub)
(craft_at pub golden_grain alcohol)
(drink_some_more )
(please_pub )
(get_wasted )
(become_drug_addict )
; cost = 27 (unit cost)
